# Generated by Django 2.1.5 on 2020-04-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JokeDuanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('nvum', models.PositiveIntegerField(blank=True, null=True)),
                ('like_num', models.PositiveIntegerField(blank=True, null=True)),
                ('no_like', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('is_hot', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'joke_duanzi',
            },
        ),
        migrations.CreateModel(
            name='JokeImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=30)),
                ('nvum', models.PositiveIntegerField(blank=True, null=True)),
                ('like_num', models.PositiveIntegerField(blank=True, null=True)),
                ('no_like', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'joke_img',
            },
        ),
    ]
